# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bf675c6a-9d92-4499-86d1-586b7610e5ba";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-bf675c6a-9d92-4499-86d1-586b7610e5ba".device = "/dev/disk/by-uuid/bf675c6a-9d92-4499-86d1-586b7610e5ba";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-bf675c6a-9d92-4499-86d1-586b7610e5ba";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-bf675c6a-9d92-4499-86d1-586b7610e5ba";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/92B8-68D2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d181ad5b-1207-4b42-9aeb-90ba65b98839"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
